#!/bin/bash

#should I do this on startvnc?
vglclient &

XFCE_PANEL_MIGRATE_DEFAULT=true startxfce4 &

#vglrun fsleyes `find $INPUT_DIR -name *.nii.gz` &
vglrun /brainstorm3/bin/R2020a/brainstorm3.command &
pid=$!

#maximize fsleyes
sleep 5
id=`wmctrl -pl | grep " $pid " | cut -f 1 -d " "`
echo $id > /id.txt
wmctrl -i -r $id -b add,fullscreen

sleep 3600
